name = "Academic"
license = "MIT"

min_version = 0.49
tags = ["academic",
        "portfolio",
        "responsive",
        "student",
        "personal",
        "university",
        "blog",
        "minimal"
        ]
features = ["academic profile",
            "research publication system",
            "projects",
            "blog",
            "teaching",
            "contact"
            "events"
            ]

[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
